language: csharp
solution: src/LaraUI.sln
mono: none
dotnet: 3.0.100

before_install:
 - msbuild-prepare

install:
 - dotnet restore src/LaraUI.sln

script:
 - msbuild /p:Configuration=Debug src/LaraUI.sln
 - dotnet test src/Test/Tests.csproj
