language: csharp
solution: src/LaraUI.sln
mono: none
dotnet: 3.0.100

install:
  - nuget restore src/LaraUI.sln

script:
 - cd src/LaraClient
 - npm install .
 - cd ..
 - cd ..
 - dotnet build --configuration Debug src/LaraUI/LaraUI.csproj
 - dotnet build --configuration Debug src/Tests/Tests.csproj
 - dotnet test src/Tests/Tests.csproj
