language: csharp
solution: src/LaraUI.sln
dotnet: 3.0.100

before
install:
 - nuget restore src/LaraUI.sln

script:
 - msbuild /p:Configuration=Debug src/LaraUI.sln
 - dotnet test src/Test/Tests.csproj
