language: csharp
solution: src/LaraUI.sln
mono: none
dotnet: 3.0.100

before_install:
 - sudo apt install nuget

install:
 - nuget Install-Package MSBuild.Microsoft.VisualStudio.Web.targets
 - nuget restore src/LaraUI.sln

script:
 - dotnet build --configuration Debug src/LaraUI.sln
 - dotnet test src/Test/Tests.csproj
