language: csharp
solution: src/LaraUI.sln
mono: none
os: windows
dotnet: 3.0.100

install:
  - nuget restore src/LaraUI.sln

script:
 - msbuild --configuration Debug src/LaraUI.sln
 - dotnet test src/Test/Tests.csproj
