language: csharp
solution: src/LaraUI.sln
mono: none
dotnet: 3.0.100

before_install:
 - sudo apt install nuget

install:
  - nuget restore src/LaraUI.sln

script:
 - echo "Debug" ? src/environment.txt
 - cd src/LaraClient
 - npm install .
 - npm run-script build
 - cd ..
 - cd ..
 - dotnet build --configuration Debug src/LaraUI/LaraUI.csproj
 - dotnet build --configuration Debug src/Tests/Tests.csproj
 - dotnet test src/Tests/Tests.csproj
