language: csharp
solution: src/LaraUI.sln
mono: none
dotnet: 3.0.100

before_install:
 - sudo apt install nuget

install:
  - nuget restore src/LaraUI.sln

script:
 - msbuild --configuration Debug src/LaraUI.sln
 - dotnet test src/Test/Tests.csproj
